### ISSUE TITLE
How to get similar reference binder

### ISSUE THREAD

**Issue by xtzhang0216** [adaptyvbio/egfr_competition_1#2]
In the similarity check, the patent number of the most similar binder is given. I am wondering how to search the ref binder based on patent number. For example USPTO:WPV81154, I cannot find it from www.uspto.gov or https://ppubs.uspto.gov/pubwebapp/static/pages/ppubsbasic.html.
thanks in advance.

**Comment by danielnzg85** [comment]
Hey @xtzhang0216, you can search the proteins with the USPTO code using the EMBL-EBI [database](https://www.ebi.ac.uk/Tools/dbfetch/) fetching tool. If you select the USPTO Protein from the Database dropdown you should be able to use the IDs we have on the tables. Ex. [USPTO:WPV81154](https://www.ebi.ac.uk/Tools/dbfetch/dbfetch?db=uspto_prt&id=WPV81154&format=default&style=default&Retrieve=Retrieve).
