### ISSUE TITLE
DNA Design for Top Binder - Tips for Synthesis Request

### ISSUE THREAD

**Issue by LRParser** [adaptyvbio/egfr_competition_1#4]
Hi,
Thanks for hosting this amazing competition!

Can you give any tips on how to express the top binder(s) in a cell-free system? For instance, consider Martin's top design:
```
SPFDLFLDRLPEQDPEMTEEGKWWAEEMKRMVGPHFEELEEYIRNNASGEELETQLWTFLIIFDSMSKIVKRYASEETRKLLDELVKKIEEAIREAEEKAKSEEEKKELMRKVGIEVIKTLAELAEVDYKVPGIDYSF
```
Can I synthesise this at e.g. Twist just adding a HIS tag at the end, and starting with an M residue (and choosing Twist's defaults to optimise for E coli), as:
```
MSPFDLFLDRLPEQDPEMTEEGKWWAEEMKRMVGPHFEELEEYIRNNASGEELETQLWTFLIIFDSMSKIVKRYASEETRKLLDELVKKIEEAIREAEEKAKSEEEKKELMRKVGIEVIKTLAELAEVDYKVPGIDYSFHHHHHH*
```
and also adding a relevant promoter, like for T7, and then express it using myTXTL kit and purify it via IMAC? Would I be likely to be testing something similar to what you tested?
Want to try to run some of these tests myself!

**Comment by danielnzg85** [comment]
Hey @LRParser,

Yeah in general the sequence you designed with the C-Terminal His, start codon, suitable non-coding region (T7 Promoter, RBS, terminator) and using an E. Coli codon optimization from any of the available vendors should work. I am not super familiar with myTXTL system but I will recommend also checking out their [handbook ](https://arborbiosci.com/wp-content/uploads/myTXTL-Handbook-v01.pdf) as it might contain also some other useful information for designing the input DNA. Also you can use their GFP plasmid control as reference to design your gene [P70a(2)-deGFP](https://www.addgene.org/184841/). You should also be able to find the coding region of the genes we used for the competition in [here](https://github.com/adaptyvbio/egfr_competition_1/blob/main/results/result_summary.csv). Let me know if you have additional questions. Happy to help.
