### ISSUE TITLE
data about round2

### ISSUE THREAD

**Issue by xtzhang0216** [adaptyvbio/egfr_competition_1#6]
Very impressive results!
Will you be releasing downloadable data for the second round of the competition? I mean the predicted structure and metrics of all binders and nonbinders? About when will it be, I can't wait to learn these binder designs!

**Comment by tJala** [comment]
Yes! Round 2 data here: https://github.com/adaptyvbio/egfr_competition_2

**Comment by xtzhang0216** [comment]
Thank you for your generous sharing!
